version: '3.8'

services:
  web:
    build: .
    container_name: splinter
    ports:
      - "80:80"
      - "22:22"
    depends_on:
      - db
    networks:
      - lab-network

  db:
    image: mysql:5.7
    container_name: splinter-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lab_db
      MYSQL_USER: php
      MYSQL_PASSWORD: zYPw7wVH7c2S74vXpLviOjavdCnkuH
    volumes:
      - ./src/sql:/docker-entrypoint-initdb.d
    networks:
      - lab-network

networks:
  lab-network:
    driver: bridge
